name: api_client
description: Api Client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  dio: ^4.0.6
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4 

dev_dependencies:
  build_runner: ^2.3.2 
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
